### ISSUE TITLE
Display of Irrelevant Model Names in Operation Configuration

### ISSUE THREAD

**Issue by SurajKamal24** [MuleSoft-AI-Chain-Project/mac-vectors#8]
While exploring the MAC Vectors Connector, I discovered an issue where model names irrelevant to the selected embeddingProviderType are displayed during operation configuration. The connector currently supports providers such as `OPENAI`, `MISTRAL_AI`, and `NOMIC`. However, all model names are shown regardless of the chosen provider. Please find the screenshot below

This can lead to confusion and potential operational failures if developers inadvertently select model names incompatible with their chosen provider.

![config](https://github.com/user-attachments/assets/c06a99c7-f91e-49fd-89d1-dc24b3ad264a)

![operation](https://github.com/user-attachments/assets/98eec779-815a-40e4-9227-793bd7bb1315)

**Comment by amirkhan-ak-sf** [comment]
Hi @SurajKamal24 

thanks for reporting this. This is known, and will be fixed in one of the upcoming releases.

**Comment by SurajKamal24** [comment]
Hi @amirkhan-ak-sf 
Thank you for acknowledging. I would be happy to contribute by adding new features to the connectors.

**Comment by amirkhan-ak-sf** [comment]
Sure, lets connect. I see you have a pull request. I want to onboard you properly to the repository. Let's connect on LinkedIn. Here is my profile https://www.linkedin.com/in/amir-khan-ak/.
